# Generated by Django 3.2.3 on 2021-05-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_retweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='total_likes',
            field=models.IntegerField(null=True),
        ),
    ]
