# Generated by Django 3.2.3 on 2021-05-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
